version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - ls -la
      - cd backend
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the application"
      - npm run build --if-present
      - echo "Running tests"
      - npm test