version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Opening backend folder"
      - cd backend/
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Running tests and type checks"
      - echo "Building the application"
      - npm run build --if-present
      - echo "Running tests"
      - npm test